import type { CrmClient, CrmProperty } from "@/lib/crm";

const NOW = "2026-03-27T09:00:00.000Z";

export const CRM_MOCK_CLIENTS: CrmClient[] = [
  {
    id: "client_maple_ridge_hoa",
    clientType: "hoa",
    companyName: "Maple Ridge HOA",
    firstName: null,
    lastName: null,
    displayName: "Maple Ridge HOA",
    primaryPhone: "(262) 555-0142",
    secondaryPhone: "(262) 555-0143",
    primaryEmail: "board@mapleridgehoa.com",
    billingEmail: "ap@mapleridgehoa.com",
    status: "active",
    preferredContactMethod: "email",
    notes: "Seasonal turf work, landscape maintenance, and snow pushes route through the HOA board.",
    tags: ["hoa", "snow", "fertilizing"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "client_keller_residence",
    clientType: "residential",
    companyName: null,
    firstName: "Sarah",
    lastName: "Keller",
    displayName: "Sarah Keller",
    primaryPhone: "(414) 555-0198",
    secondaryPhone: null,
    primaryEmail: "sarah.keller@email.com",
    billingEmail: "sarah.keller@email.com",
    status: "active",
    preferredContactMethod: "text",
    notes: "Primary residential account with fertilizing and recurring maintenance interest.",
    tags: ["residential", "maintenance"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "client_brookfield_parks",
    clientType: "municipal",
    companyName: "City of Brookfield Parks",
    firstName: "Dana",
    lastName: "Lopez",
    displayName: "City of Brookfield Parks",
    primaryPhone: "(262) 555-0111",
    secondaryPhone: "(262) 555-0112",
    primaryEmail: "d.lopez@brookfield.gov",
    billingEmail: "invoices@brookfield.gov",
    status: "active",
    preferredContactMethod: "billing_email",
    notes: "Municipal grounds account with multiple service locations and snow escalation expectations.",
    tags: ["municipal", "multi-site"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "client_northside_commerce",
    clientType: "commercial",
    companyName: "Northside Commerce Center",
    firstName: "Eric",
    lastName: "Pruitt",
    displayName: "Northside Commerce Center",
    primaryPhone: "(414) 555-0220",
    secondaryPhone: null,
    primaryEmail: "epruitt@northsidecommerce.com",
    billingEmail: "ap@northsidecommerce.com",
    status: "inactive",
    preferredContactMethod: "phone",
    notes: "Former fertilizing-heavy site now paused pending budget review.",
    tags: ["commercial", "inactive"],
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const CRM_MOCK_PROPERTIES: CrmProperty[] = [
  {
    id: "property_maple_ridge_clubhouse",
    clientId: "client_maple_ridge_hoa",
    propertyName: "Clubhouse & Entry Beds",
    addressLine1: "1880 Maple Ridge Dr",
    addressLine2: null,
    city: "New Berlin",
    state: "WI",
    postalCode: "53151",
    country: "US",
    propertyType: "commercial",
    lawnSizeSqft: 62000,
    acreage: 1.42,
    gatePresent: false,
    lockedGate: false,
    petsPresent: false,
    entryNotes: "Crew can stage near the west clubhouse lot before 8 AM.",
    siteNotes: "High-visibility entry beds, clubhouse lawn, and sidewalk edges.",
    billingSameAsServiceAddress: false,
    billingAddressLine1: "PO Box 411",
    billingAddressLine2: null,
    billingCity: "New Berlin",
    billingState: "WI",
    billingPostalCode: "53151",
    billingCountry: "US",
    isActive: true,
    routeGroup: "West HOA",
    snowPriority: "priority_1",
    fertilizingPreferences: "Slow-release preferred around clubhouse beds.",
    maintenanceContractLink: "Annual grounds package",
    latitude: null,
    longitude: null,
    serviceTemplates: ["grounds-maintenance", "snow-push"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "property_maple_ridge_north",
    clientId: "client_maple_ridge_hoa",
    propertyName: "North Entrance",
    addressLine1: "4205 S Moorland Rd",
    addressLine2: null,
    city: "New Berlin",
    state: "WI",
    postalCode: "53151",
    country: "US",
    propertyType: "other",
    lawnSizeSqft: 14000,
    acreage: 0.32,
    gatePresent: false,
    lockedGate: false,
    petsPresent: false,
    entryNotes: null,
    siteNotes: "Smaller entry monument area with irrigation heads close to curb.",
    billingSameAsServiceAddress: true,
    billingAddressLine1: null,
    billingAddressLine2: null,
    billingCity: null,
    billingState: null,
    billingPostalCode: null,
    billingCountry: null,
    isActive: true,
    routeGroup: "West HOA",
    snowPriority: "priority_2",
    fertilizingPreferences: null,
    maintenanceContractLink: "Annual grounds package",
    latitude: null,
    longitude: null,
    serviceTemplates: ["entry-detail"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "property_keller_home",
    clientId: "client_keller_residence",
    propertyName: "Keller Residence",
    addressLine1: "9123 Glenwood Ct",
    addressLine2: null,
    city: "Muskego",
    state: "WI",
    postalCode: "53150",
    country: "US",
    propertyType: "residential",
    lawnSizeSqft: 18500,
    acreage: 0.42,
    gatePresent: true,
    lockedGate: true,
    petsPresent: true,
    entryNotes: "Text before arrival. Back gate latch sticks when wet.",
    siteNotes: "Family prefers edging every other visit and low-noise equipment before 9 AM.",
    billingSameAsServiceAddress: true,
    billingAddressLine1: null,
    billingAddressLine2: null,
    billingCity: null,
    billingState: null,
    billingPostalCode: null,
    billingCountry: null,
    isActive: true,
    routeGroup: "Muskego South",
    snowPriority: "priority_2",
    fertilizingPreferences: "Avoid application near raised herb beds.",
    maintenanceContractLink: "Recurring maintenance proposal",
    latitude: null,
    longitude: null,
    serviceTemplates: ["residential-maintenance", "fert-program"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "property_brookfield_admin",
    clientId: "client_brookfield_parks",
    propertyName: "Parks Admin Campus",
    addressLine1: "2000 Greenway Ave",
    addressLine2: null,
    city: "Brookfield",
    state: "WI",
    postalCode: "53045",
    country: "US",
    propertyType: "multi_site",
    lawnSizeSqft: 98000,
    acreage: 2.25,
    gatePresent: true,
    lockedGate: false,
    petsPresent: false,
    entryNotes: "Coordinate with parks staff if trucks need the rear yard entrance.",
    siteNotes: "Admin campus, trail edge mowing, and seasonal annual beds.",
    billingSameAsServiceAddress: false,
    billingAddressLine1: "100 City Hall Plaza",
    billingAddressLine2: "Accounts Payable",
    billingCity: "Brookfield",
    billingState: "WI",
    billingPostalCode: "53045",
    billingCountry: "US",
    isActive: true,
    routeGroup: "Municipal Core",
    snowPriority: "priority_1",
    fertilizingPreferences: null,
    maintenanceContractLink: "Municipal grounds agreement",
    latitude: null,
    longitude: null,
    serviceTemplates: ["municipal-maintenance", "snow-route"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "property_northside_lot_a",
    clientId: "client_northside_commerce",
    propertyName: "Lot A & Frontage",
    addressLine1: "7400 Commerce Pkwy",
    addressLine2: "Building A",
    city: "Milwaukee",
    state: "WI",
    postalCode: "53224",
    country: "US",
    propertyType: "commercial",
    lawnSizeSqft: 44000,
    acreage: 1.01,
    gatePresent: true,
    lockedGate: true,
    petsPresent: false,
    entryNotes: "Property manager must be called before any after-hours access.",
    siteNotes: "Inactive account but keep frontage notes for possible reactivation.",
    billingSameAsServiceAddress: true,
    billingAddressLine1: null,
    billingAddressLine2: null,
    billingCity: null,
    billingState: null,
    billingPostalCode: null,
    billingCountry: null,
    isActive: false,
    routeGroup: "Commerce North",
    snowPriority: "priority_3",
    fertilizingPreferences: null,
    maintenanceContractLink: null,
    latitude: null,
    longitude: null,
    serviceTemplates: ["commercial-maintenance"],
    createdAt: NOW,
    updatedAt: NOW,
  },
];
